'use strict';
const base='https://github.com/aitullalimon/';
const projects=[
{title:'Creative Writing LLM Benchmark',repo:'creative-writing-llm-benchmark',category:'AI & ML',tags:['Next.js','TypeScript','LiteLLM'],description:'Compare language models on creative writing with an LLM judge, theme-coherence scores, leaderboards, and visual analytics.',detail:'A Next.js application with model routing through LiteLLM, a judge-based evaluation pipeline, interactive model comparisons, and persistent run history. This repository documents theme-coherence scoring on a 0–10 scale.',kind:'Public repository'},
{title:'End-to-End ML Pipeline',repo:'end-to-end-ml-production-pipeline',category:'AI & ML',tags:['Python','scikit-learn','Docker'],description:'A reusable classification and regression workflow, from exploratory analysis and preprocessing to evaluation and batch inference.',detail:'Includes preprocessing with ColumnTransformer, cross-validation, model metrics, joblib model persistence, command-line inference, and CSV prediction exports. Docker support makes the workflow easier to reproduce.',kind:'Public repository'},
{title:'Earthquake Risk Predictor · Japan',repo:'Earthquake-Risk-Predictor---Japan',category:'AI & ML',tags:['R','Random Forest','Leaflet'],description:'An academic risk-classification prototype with a bilingual interface, Japanese prefecture selection, and seismic map visualizations.',detail:'Uses an R Plumber API and Random Forest with a JavaScript frontend, Leaflet maps, Chart.js visualizations, and USGS seismic data. My broader academic work also explored SHAP explanations and safe-route optimization. The project is an academic prototype for studying risk support.',kind:'Academic prototype / Public repository'},
{title:'LiteLLM Creative Writing Evaluation',repo:'LiteLLM-Creative-Writing-Benchmarking',category:'AI & ML',tags:['React / Vite','Express','OpenRouter'],description:'A second benchmark implementation scoring theme coherence, creativity, fluency, and engagement across model outputs.',detail:'A React/Vite frontend and Express server use OpenAI-compatible routing through LiteLLM or OpenRouter. The documented workflow offers live evaluation and a separate demo mode with mock scores, charts, and a leaderboard.',kind:'Public repository'},
{title:'Working Hours · iOS',repo:'WorkingHoursApp',category:'Apps',tags:['Swift','SwiftUI','iOS'],description:'Track working hours across companies, set hourly rates, and review monthly or custom-range earnings summaries.',detail:'A SwiftUI app for managing companies and time entries. Designed around practical time and earnings tracking for freelancers, contractors, and student part-time work. The README lists payment tracking as a future feature.',kind:'Public repository'},
{title:'Working Hours · Web',repo:'WorkingHoursWeb-Database',category:'Apps',tags:['JavaScript','localStorage','CSV / JSON'],description:'A browser-based job-hours calculator with company records, overtime, hourly or point-based pay, and data exports.',detail:'The web interface supports breaks, transport allowances, overtime thresholds and multipliers, company-specific rates, and date-filtered entries. Data is stored in localStorage, with CSV exports and JSON backup/import.',kind:'Public repository'},
{title:'Cultural Awareness in Japan',repo:'Cultural-Awareness-in-Japan',category:'Web',tags:['HTML','CSS','Culture'],description:'An educational website introducing Japanese culture, lifestyle, festivals, cuisine, etiquette, and everyday rules.',detail:'A multi-page cultural guide with sections on Japan, traditions, cuisine, and social norms. Built to help international students and visitors explore and appreciate Japanese culture.',kind:'Public repository'},
{title:'Bangladeshi Coders · Group Profile',repo:'Group-Profile-Bangladeshi-Coders-',category:'Web',tags:['HTML','CSS','Team project'],description:'A group website introducing a team of Bangladeshi KCGI students through profiles and a shared project identity.',detail:'Includes a team overview and individual member pages. The site identifies my role as developer in this collaborative KCGI group project.',kind:'Public repository / Team project'},
{title:'Web Programming Foundations',repo:'Web-Pro-w2-test2024',category:'Web',tags:['HTML','Coursework'],description:'An early web-programming exercise practicing lists, nested content, definitions, images, and links.',detail:'A small 2024 coursework repository demonstrating basic HTML document structure and content organization. Included here as part of my development journey.',kind:'Public repository / Coursework'},
{title:'Explore Bangladesh',repo:'Explore-Bangladesh',category:'Web',tags:['Repository scaffold'],description:'An early repository named Explore Bangladesh, currently containing a license without an application implementation.',detail:'At the October 2026 review, the public repository contained only a LICENSE file. It is included for completeness as a repository scaffold.',kind:'Public repository / Scaffold'},
{title:'Freelance & Research Collaboration',repo:'Freelance-Research-Collaboration',category:'Research',tags:['Data analysis','ML','Visualization'],description:'A collaboration profile describing my work in data analysis, machine learning, research support, and analytical web apps.',detail:'A README-based overview of research and freelance services, with examples in risk modeling, evaluation, interpretability, and reporting. This is a collaboration profile rather than a software application.',kind:'Public repository / Profile'},
{title:'Japanese Job Market Suitability Predictor',category:'AI & ML',tags:['Bilingual UI','Chart.js','PDF export'],description:'A suitability-scoring prototype with English/Japanese views, score visualizations, tabular results, and PDF report export.',detail:'A project exploring how to present job-market suitability results through an accessible interface. Features discussed in my project work include gauge-style scores, charts, an Excel-like results table, and downloadable PDF reports.',kind:'Additional project'},
{title:'Ocean-Wave Power Generation',category:'Research',tags:['Renewable energy','Engineering','Bachelor’s thesis'],description:'My undergraduate thesis explored a power generation system using ocean-wave energy.',detail:'An engineering research project on wave-driven power generation. It formed an early foundation for my interest in applied systems, analytical thinking, and practical problem solving.',kind:'Academic thesis'},
{title:'Bangladeshi Community Media Research',category:'Research',tags:['Desk research','Source verification','Excel'],description:'Research on ethnic media and community influencers serving Bangladeshis in Japan, organized into structured research tables.',detail:'Applied research covering media organizations and influencers, with URLs, posting activity, recent-content analysis, and collaboration context. The work emphasized source checking, deduplication, and clearly documented findings.',kind:'Applied research'},
{title:'Comparative Decarbonisation Research Support',category:'Research',tags:['Comparative analysis','Process tracing','EU ETS'],description:'Research and writing support examining Denmark and the Netherlands under the EU Emissions Trading System, 2005–2020.',detail:'Collaborative support for a comparative study using a most-similar-systems design, within-case process tracing, and congruence analysis. Focus areas included industrial policy, state–incumbent relations, evidence organization, and methodological clarity.',kind:'Research collaboration'}
];
const grid=document.querySelector('#project-grid'),search=document.querySelector('#search'),dialog=document.querySelector('#details');
let category='All';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function art(i){const a=i%4;let shapes='';if(a===0)shapes='<path d="M40 100V65H90V85H135V42H185V60H235V25H290"/><path d="M40 110H290" opacity=".3"/>';if(a===1)shapes='<circle cx="165" cy="68" r="40"/><ellipse cx="165" cy="68" rx="85" ry="28"/><ellipse cx="165" cy="68" rx="28" ry="55"/>';if(a===2)shapes='<rect x="95" y="23" width="140" height="90" rx="7"/><path d="M110 43H220M110 58H180M110 74H210M110 91H160"/>';if(a===3)shapes='<path d="M70 94L115 45L165 82L215 33L260 90M115 45L215 33M70 94L165 82L260 90"/><circle cx="70" cy="94" r="4"/><circle cx="115" cy="45" r="4"/><circle cx="165" cy="82" r="4"/><circle cx="215" cy="33" r="4"/><circle cx="260" cy="90" r="4"/>';return `<svg viewBox="0 0 330 135" aria-hidden="true"><g fill="none" stroke="var(--blue)" stroke-width="1.4">${shapes}</g></svg>`;}
function render(){const q=search.value.toLowerCase().trim();const filtered=projects.map((p,i)=>({...p,i})).filter(p=>(category==='All'||p.category===category)&&[p.title,p.description,...p.tags].join(' ').toLowerCase().includes(q));grid.innerHTML=filtered.length?filtered.map(p=>`<article class="card"><div class="card-art"><span class="card-code">PROJECT / ${String(p.i+1).padStart(2,'0')}</span>${art(p.i)}</div><div class="card-body"><div class="card-category">${esc(p.category)}</div><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><div class="tags">${p.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="card-footer"><button class="text-button" data-detail="${p.i}" aria-label="View details for ${esc(p.title)}">Explore project ↗</button>${p.repo?`<a href="${base+encodeURIComponent(p.repo)}" target="_blank" rel="noopener noreferrer">Source ↗</a>`:'<span class="mono" style="font-size:9px;color:var(--muted)">Additional work</span>'}</div></div></article>`).join(''):'<p class="empty">No matching projects. Try another keyword or category.</p>';document.querySelector('#result-count').textContent=`${filtered.length} of ${projects.length} entries · Public repositories reviewed October 2026`;}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render();}));search.addEventListener('input',render);
grid.addEventListener('click',e=>{const b=e.target.closest('[data-detail]');if(!b)return;const p=projects[Number(b.dataset.detail)];document.querySelector('#detail-content').innerHTML=`<div class="eyebrow">${esc(p.kind)}</div><h2>${esc(p.title)}</h2><p>${esc(p.description)}</p><p>${esc(p.detail)}</p><div class="tags">${p.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>${p.repo?`<a class="btn" href="${base+encodeURIComponent(p.repo)}" target="_blank" rel="noopener noreferrer">View repository ↗</a>`:''}`;dialog.showModal();});dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
try{if(localStorage.getItem('portfolio-theme')==='light')document.body.classList.add('light');}catch{}
document.querySelector('#theme').addEventListener('click',()=>{document.body.classList.toggle('light');try{localStorage.setItem('portfolio-theme',document.body.classList.contains('light')?'light':'dark');}catch{}});
function progress(){const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('#progress').style.width=(max>0?scrollY/max*100:0)+'%';}window.addEventListener('scroll',progress,{passive:true});window.addEventListener('resize',progress);document.querySelector('#project-total').textContent=projects.length;render();progress();
